apiVersion: v2
name: open-idp-apps
description: Applications installed by ArgoCD
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
  - name: argocd-app-of-apps
    version: 0.1.0
    repository: oci://registry-1.docker.io/jasoncarneiro
    alias: apps
